version: '3'
services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: parcelApp
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  app:
    build: .
    container_name: app
    ports:
      - 4000:4000
    expose:
      - 4000
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/parcelApp
    depends_on:
      - db

